### ISSUE TITLE
Extension Login Error

### ISSUE THREAD

**Issue by The-Cookie-Hub** [projectdiscovery/nuclei-ai-extension#13]
Hey there.

I worked with the extension for 1 day and it worked wonderful. But now it asks me to login again. Everytime I log in I get an error. I already reinstalled the extension once which helped nothing. 

Please help me.
![IMG_2770](https://github.com/projectdiscovery/nuclei-ai-extension/assets/166227969/a9bf4c50-6cb0-48e8-a13b-f6dcb45b78d6)
![IMG_2771](https://github.com/projectdiscovery/nuclei-ai-extension/assets/166227969/92837d72-4db9-4ad3-b353-edbe8d278a47)

**Comment by Stealth-Sec** [comment]
![image](https://github.com/projectdiscovery/nuclei-ai-extension/assets/166227969/49bc1f03-87a4-4223-8b86-c1bb9e6311dc)

**Comment by ehsandeep** [comment]
@The-Cookie-Hub @parthmalhotra this is now fixed.
