### ISSUE TITLE
cloud.projectdiscovery.io is not sending link verification email

### ISSUE THREAD

**Issue by edoardottt** [projectdiscovery/nuclei-ai-extension#8]
Sorry team for the issue in the 'wrong repo' (here it's mentioned so it could be relevant for others), but I think it's the fastest way to contact you.

I'm trying to sign up on [cloud.projectdiscovery.io](https://cloud.projectdiscovery.io/) and the page tells me `We have sent you an email with verification link`, but there isn't in my inbox 😅

p.s. y I've checked spam folder

**Comment by olearycrew** [comment]
@edoardottt are you still struggling with this? If so, can you join our Discord server as I have some questions for you - https://nux.gg/discord

**Comment by edoardottt** [comment]
Thanks @olearycrew , just tried again and it seems fixed. You can close the issue iyw.
